name: Build CI

on: [push, pull_request, workflow_dispatch, workflow_call]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [template_debug, template_release]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - target: template_debug
            target-type: debug
          - target: template_release
            target-type: release
    name: ${{ matrix.platform }} ${{ matrix.target-type }} build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install SCons
        uses: ./.github/composite/scons
      - name: Build library
        run: scons platform=${{ matrix.platform }} target=${{ matrix.target }}
      - name: Upload artificat
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-${{ matrix.target-type }}-${{ github.sha }}
          if-no-files-found: error
          path: bin/

